image:
  repository: barthelemy/azure-snapshoter
  tag: latest
  pullPolicy: IfNotPresent
failedJobsHistoryLimit: 3
successfulJobsHistoryLimit: 3
concurrencyPolicy: Forbid
restartPolicy: OnFailure

schedule: "* * * * *"

# optional : how long before to delete the snapshot, in plain english : "1 month", "5 days"...
retention:

# required values
resource_group:
location:
snapshot_base_name:

# optional (either disk_id or disk_tag is required)
disk_id:
disk_tag:

use_secret: true
sp_id:
sp_password:
tenant_id:

