{{- if .Values.use_secret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "azure-snapshoter.fullname" . }}
  labels:
    app: {{ template "azure-snapshoter.fullname" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
type: Opaque
data:
  sp_id: {{ required "sp_id is required" .Values.sp_id | b64enc | quote }}
  sp_password: {{ required "sp_password is required" .Values.sp_password | b64enc | quote }}
  tenant_id: {{ required "tenant_id is required" .Values.tenant_id | b64enc | quote }}
{{- end }}